### PR TITLE
Fix session loss by storing cookies in IndexDB

### LINKED ISSUE #97: Cookies tracked in CGI worker are lost, logging the user out
PhpCgiBase tracks cookies to pass them back to Drupal.

```
// constructor
this.cookies    = cookies    || new Map;


// request begin
putEnv(php, 'HTTP_COOKIE', [...this.cookies.entries()].map(e => `${e[0]}=${e[1]}`).join(';') );

// request handle response
if(parsedResponse.headers['Set-Cookie'])
		{
			const raw = parsedResponse.headers['Set-Cookie'];
			const semi  = raw.indexOf(';');
			const equal = raw.indexOf('=');
			const key   = raw.substr(0, equal);
			const value = raw.substr(1 + equal, -1 + semi - equal);

			this.cookies.set(key, value,);
		}
```

I waited for the error to happen, where I got access denied. `this.cookies` was empty

### PR DESCRIPTION
**Pull request by mglaman**
fixes #97

### CODE REVIEW

File: public/drupal-cgi-worker.mjs [hunk 1]
```diff
@@ -1,6 +1,23 @@
...
+        if (value === 'deleted') {
+            super.delete(key)
+        } else {
+            super.set(key, value)
+        }
+    }
+}
+
+const cookies = new CookieMap;
+
```
Comment (mglaman) [inline public/drupal-cgi-worker.mjs:20]: document that this exists purely to handle deletion of cookies

File: public/drupal-cgi-worker.mjs [hunk 2]
```diff
@@ -47,9 +64,20 @@ export class DrupalCgiWorker extends PhpCgiWorker {
...
+    async _beforeRequest() {
+        await super._beforeRequest();
+        // sync cookie data from session or local storage to `this.cookies`
+    }
+
+    async _afterRequest() {
+        await super._afterRequest();
+        // sync cookie data from `this.cookies` to session or local storage
+    }
```
Comment (mglaman) [inline public/drupal-cgi-worker.mjs:80]: todo the sync

needs to be purged if a new session is started as well

Comment (mglaman) [reply public/drupal-cgi-worker.mjs:80]: also, definitely use local storage so it persists for more use cases
